### ISSUE TITLE
Memory leak in msedgewebview2.exe on windows

### ISSUE THREAD

**Issue by mgholam** [tryphotino/photino.NET#48] opened 2021-05-28 03:42 UTC
The sample photino demo app leaks memory at an alarming rate after the first pop message box is closed ("dynamically inserted javascript") over 1Gb after 10 secs idle and consumes cpu cycles constantly.

**Comment by MikeYeager** [comment] 2021-05-28 14:22
Thanks for the report. We haven't seen this ourselves. Based on the subject line, you're on Windows. Which sample are you running? We have very little control over the memory allocated to the WebView2 control, but we will look into it in case it's caused by one of our callbacks somehow.

On my machine, the Edge browser uses between 400 MB and 1GB and 25-30% CPU just to open the https://tryphotino.io page with dev tools open. The page has an animated .gif similar to the one on some of the sample apps and collects some information for Microsoft Clarity. Chrome is about the same. I'll check this against the sample app, but I do want to be sure which app you're running.

Thanks,
Mike


From: Mehdi Gholam ***@***.***>
Sent: Thursday, May 27, 2021 9:43 PM
To: tryphotino/photino.NET ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tryphotino/photino.NET] Memory leak in msedgewebview2.exe on windows (#48)


The sample photino demo app leaks memory at an alarming rate after the first pop message box is closed ("dynamically inserted javascript") over 1Gb after 10 secs idle and consumes cpu cycles constantly.

-

**Comment by mgholam** [comment] 2021-05-28 14:59
Running the "HelloPhotino.NET App"

The sample app running in the task manager, after I clicked the message box to go away it starts consuming cycles and memory :

https://user-images.githubusercontent.com/460565/120003292-da42de80-bfea-11eb-9e84-2b370d768b88.mp4

**Comment by MikeYeager** [comment] 2021-05-28 15:55
Thank you Mehdi. We'll check it out.

Mike

**Comment by MikeYeager** [comment] 2021-06-10 16:12
We've been able to reproduce this on Windows (not Mac or Linux). It has something to do with the JavaScript interop and we're looking into it. Thanks for the bug report.

**Comment by mgholam** [comment] 2021-06-10 16:35
Great thanks!

**Comment by mgholam** [comment] 2021-07-01 04:58
Hi, any progress on this?

**Comment by MikeYeager** [comment] 2021-07-01 15:36
Yes, V2 for Windows is in testing now as we finish up Linux and get ready to tackle mac. So far, no memory leaks! This appears to be fixed for V2.

**Comment by mgholam** [comment] 2021-07-09 05:55
When are you planning to release this?

**Comment by MikeYeager** [comment] 2021-07-09 16:42
@mgholam As soon as possible! We ran into a snag with the webview in Linux when we open multiple windows and have reached out to the webkit2GTK developers for a solution. Other than that, Linux is just about finished and we're actively working on the mac code. Hard to say exactly when, but it's not for lack of effort. If we can't find a solution for the Linux issue, we'll release anyway with a developer note. It all depends on how quickly we can get the mac code updated now.

**Comment by ottodobretsberger** [comment] 2021-08-30 17:52
@mgholam this should be fixed with the release of v2. Please let us know if you still encounter this issue.

**Closed by ottodobretsberger** 2021-08-30 17:52 UTC
Labels: bug, Windows

**Comment by Kuinox** [comment] 2022-01-24 01:21
Hello,
I tried the last release and got the same issue described here: 
Closing the alert popup in the .NET Sample lead to a lot of memory allocated:
![image](https://user-images.githubusercontent.com/18743295/150707368-2479f62d-4e84-4caf-af86-b9858b0e0fc3.png)

Which get later cleaned up by the GC.

**Comment by MikeYeager** [comment] 2022-01-27 16:17
@Kuinox We can't reproduce this. When we initially close the alert, it jumps from about 80MB of memory to almost 300MB, but then comes back down to about 90MB after a few seconds. Maybe a tool like JetBrains DotTrace or DotMemory could help us pinpoint the issue on your system? Do you have access to such tools?

**Comment by Kuinox** [comment] 2022-01-27 21:30
Well, I found out the issue, it's edge acting up:  
![image](https://user-images.githubusercontent.com/18743295/151445542-5deef721-0209-4b81-9f34-fe57c5228992.png)
For some reason, it doesn't like the spinning SVG, and it looks like related to refresh rate (on a 60Hz screen it doesn't go past 300MB).  

>  but then comes back down to about 90MB after a few seconds.

To me it come back at 200MB (probably due to the different refreshrate),
It also eat up 10% of the cpu when it spin :/

**Comment by bcrosnier** [comment] 2022-01-27 21:59
Can repro on a high-display rates monitor (using 240 Hz here) with the same runtime. After waiting a bit, upon clicking on OK on the first alert, WebView2's renderer memory footprint jumps *tremendously*.

![image](https://user-images.githubusercontent.com/1652112/151447127-819fcc52-9a23-45c8-ae50-e3774e311aa7.png)

This is more of an issue with [WebView2](https://github.com/MicrosoftEdge/WebView2Feedback) (and possibly Chromium) rather than with Photino, but I guess it's nice to be aware of it.

And in case there is any doubt, this is most likely caused by SVG SMIL animation rendering/repainting. Removing the `<animateTransform>` element from `photino-logo.svg` stops both CPU and RAM from jumping unexpectedly.  
Sample notwithstanding, if this becomes an issue in your app, try using different methods (like splitting the SVG into separate parts, so that animation can occur on one part without repainting the whole thing constantly, switching to CSS, and checking if hardware rendering is enabled).

**Comment by Kuinox** [comment] 2022-01-28 21:44
> This is more of an issue with WebView2 (and possibly Chromium)

Yes, I reproduced the issue with Chrome, the rotating SVG eats 1.5GB of RAM ^^'
